version: "2"

linters:
  default: standard
  enable:
    - exhaustive
    - revive
    - misspell
    - revive
    - unconvert
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
