linters-settings:
  gofumpt:
    module-path: github.com/rbrady98/steiger


linters:
  enable:
  - unused
  - gosimple
  - bodyclose
  - gocritic
  - gofumpt
  - govet
  - ineffassign
  - importas
  - misspell
  - staticcheck
  - prealloc
