// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: joke.sql

package sqlitedb

import (
	"context"
)

const createJoke = `-- name: CreateJoke :exec
INSERT INTO jokes (
    joke, nsfw, created_at
) VALUES (
    ?, ?, datetime('now')
)
`

type CreateJokeParams struct {
	Joke string
	Nsfw bool
}

func (q *Queries) CreateJoke(ctx context.Context, arg CreateJokeParams) error {
	_, err := q.db.ExecContext(ctx, createJoke, arg.Joke, arg.Nsfw)
	return err
}

const getJoke = `-- name: GetJoke :one
SELECT id, joke, nsfw, created_at FROM jokes
WHERE id = ? LIMIT 1
`

func (q *Queries) GetJoke(ctx context.Context, id int64) (Joke, error) {
	row := q.db.QueryRowContext(ctx, getJoke, id)
	var i Joke
	err := row.Scan(
		&i.ID,
		&i.Joke,
		&i.Nsfw,
		&i.CreatedAt,
	)
	return i, err
}

const listJokes = `-- name: ListJokes :many
SELECT id, joke, nsfw, created_at FROM jokes
LIMIT 50
`

func (q *Queries) ListJokes(ctx context.Context) ([]Joke, error) {
	rows, err := q.db.QueryContext(ctx, listJokes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Joke
	for rows.Next() {
		var i Joke
		if err := rows.Scan(
			&i.ID,
			&i.Joke,
			&i.Nsfw,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
